# Generated by Django 4.0 on 2021-12-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='surname',
            new_name='postal_zip',
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
