# Generated by Django 4.0 on 2022-01-21 09:39

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(default=builtins.id, max_length=64, verbose_name='Имя баннера')),
                ('Image', models.ImageField(upload_to='static/static_dev/media/site_banners/', verbose_name='Фото')),
                ('placed_on', models.CharField(choices=[('Главная страница', 'Главная страница'), ('Страница товара', 'Страница товара'), ('Другое', 'Другое')], default='Главная страница', max_length=40, verbose_name='На какой странице расположен баннер')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннеры',
            },
        ),
    ]
