# Generated by Django 4.0 on 2022-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitebanners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_name',
            field=models.CharField(default='<built-in function id>', max_length=64, verbose_name='Имя баннера'),
        ),
    ]
