# Generated by Django 4.0 on 2021-12-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orderz', '0002_order_customer_address_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinorder',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
    ]
